const $=s=>document.querySelector(s);let notes=JSON.parse(localStorage.vn_notes||"null")||[{text:"Проверить производство",done:false},{text:"Позвонить поставщику",done:false},{text:"Идея нового проекта",done:false}];let groups=JSON.parse(localStorage.vn_groups||"null")||[{name:"Купить для производства",tasks:["Купить материалы","Заказать упаковку"]},{name:"Артём Мишин",tasks:["Проверить список задач"]},{name:"Алексей",tasks:[]},{name:"Дима",tasks:[]}];function save(){localStorage.vn_notes=JSON.stringify(notes);localStorage.vn_groups=JSON.stringify(groups)}function render(){let q=$("#search").value.toLowerCase();$("#notesList").innerHTML=notes.filter(n=>n.text.toLowerCase().includes(q)).map((n,i)=>`<div class="note ${n.done?"done":""}"><button class="check" data-i="${i}">✓</button><div class="txt">${esc(n.text)}</div></div>`).join("");document.querySelectorAll(".check").forEach(b=>b.onclick=()=>{notes[b.dataset.i].done=!notes[b.dataset.i].done;save();render()});$("#groups").innerHTML=groups.map((g,i)=>`<div class="group"><div class="ghead"><b>${esc(g.name)}</b><span class="count">${g.tasks.length}</span></div><div class="body">${g.tasks.map(t=>`<div class="task">${esc(t)}</div>`).join("")}</div></div>`).join("");document.querySelectorAll(".ghead").forEach(h=>h.onclick=()=>h.parentNode.classList.toggle("open"))}function esc(s){return s.replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}$("#search").oninput=render;render();

let rec=null,listening=false,buffer="";function start(){if(listening)return;if(!("webkitSpeechRecognition"in window||"SpeechRecognition"in window)){ $("#vstatus").textContent="Распознавание речи недоступно";return}let R=window.SpeechRecognition||window.webkitSpeechRecognition;rec=new R();rec.lang="ru-RU";rec.continuous=true;rec.interimResults=true;buffer="";listening=true;$("#voice").classList.add("listening");$("#vtitle").textContent="Слушаю…";$("#vstatus").textContent="Говорите";rec.onresult=e=>{let interim="";for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)buffer+=e.results[i][0].transcript+" ";else interim+=e.results[i][0].transcript}$("#vstatus").textContent=interim||"Говорите"};rec.onerror=e=>$("#vstatus").textContent="Ошибка: "+e.error;try{rec.start()}catch{}}function stop(){if(!rec)return;listening=false;try{rec.stop()}catch{}$("#voice").classList.remove("listening");$("#vtitle").textContent="Голосовой ввод";$("#vstatus").textContent="Нажмите или удерживайте, чтобы диктовать";let t=buffer.trim();buffer="";if(!t)return;let low=t.toLowerCase();if(/удалить последнее слово|удали последнее слово/.test(low)){if(notes.length)notes[0].text=notes[0].text.trim().replace(/\s+\S+$/,"");if(!notes[0]?.text)notes.shift()}else if(/^(сделано|выполнено|готово)/.test(low)){if(notes.length)notes[0].done=true}else if(/перенести.*завтра|на завтра/.test(low)){if(notes.length)notes[0].text+=" · завтра"}else{notes.unshift({text:t,done:false})}save();render()}$("#mic").onpointerdown=e=>{e.preventDefault();e.stopPropagation();try{$("#mic").setPointerCapture(e.pointerId)}catch{};start()};["pointerup","pointercancel"].forEach(x=>$("#mic").addEventListener(x,e=>{e.preventDefault();e.stopPropagation();stop()}));$("#voice").onclick=e=>{if(e.target!==$("#mic"))listening?stop():start()};

function modal(x){$("#content").innerHTML=x;$("#modal").classList.remove("hidden")}$("#close").onclick=()=>$("#modal").classList.add("hidden");$("#settings").onclick=()=>modal("<h2>Настройки</h2><button class=action>Язык: Русский</button><button class=action>Аудио не сохранять</button><button class=action>Хранение: на устройстве</button>");$("#calendar").onclick=()=>modal("<h2>Календарь</h2><p>Выберите дату для просмотра задач.</p><button class=action>Сегодня</button><button class=action>Завтра</button>");$("#calc").onclick=()=>modal("<h2>Калькулятор</h2><input id=x class=field placeholder='125*8' inputmode=decimal><button class=action id=go>Посчитать</button><p id=r></p>");document.addEventListener("click",e=>{if(e.target.id=="go")try{$("#r").textContent="= "+Function("return "+$("#x").value)()}catch{$("#r").textContent="Ошибка"}});$("#theme").onclick=()=>document.body.classList.toggle("light");$("#employees").onclick=()=>modal("<h2>Сотрудники</h2><div class=employee>Артём Мишин</div><div class=employee>Алексей</div><div class=employee>Дима</div><button class=action>＋ Добавить сотрудника</button>");$("#notebook").onclick=()=>modal("<h2>Блокнот</h2><div style='height:45vh;background-image:linear-gradient(#333 1px,transparent 1px),linear-gradient(90deg,#333 1px,transparent 1px);background-size:24px 24px'></div>");
const micEl=$("#mic"), voiceEl=$("#voice");
[micEl,voiceEl].forEach(el=>{
  if(!el) return;
  el.addEventListener("contextmenu",e=>{e.preventDefault();e.stopPropagation();return false});
  el.addEventListener("selectstart",e=>{e.preventDefault();e.stopPropagation()});
  el.addEventListener("dragstart",e=>{e.preventDefault();e.stopPropagation()});
  el.addEventListener("touchstart",e=>{ if(el===micEl) e.preventDefault(); },{passive:false});
});
document.addEventListener("visibilitychange",()=>{
  if(document.hidden && listening) stop();
});
window.addEventListener("pagehide",()=>{ if(listening) stop(); });
