const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)],KEY='vn4';
let d=JSON.parse(localStorage.getItem(KEY)||'null')||{notes:[{id:1,t:'Идея для проекта',b:'Быстро записывать мысли голосом и превращать их в задачи.',m:'Сегодня, 14:32',f:false,task:false},{id:2,t:'Позвонить поставщику',b:'Уточнить сроки и стоимость материалов.',m:'Сегодня, 15:10',f:true,task:true},{id:3,t:'Проверить оборудование',b:'Подготовить всё к завтрашнему мастер-классу.',m:'Завтра, 10:00',f:false,task:true}],groups:[{n:'Купить для производства',i:'🛒',c:'orange',a:['Краска','Саморезы','Перчатки']},{n:'Выполненные',i:'✓',c:'green',a:['Подготовить оборудование']}],emps:[{n:'Артём',r:'Мастер цеха',ts:[['Проверить материалы','Сегодня 10:00',0],['Подготовить оборудование','Сегодня 14:00',0],['Забрать заказ у поставщика','Завтра 11:00',0],['Провести инструктаж','7 августа 16:30',1]]},{n:'Мишин',r:'Производство',ts:[['Проверить станок','Сегодня 12:00',0],['Закупить расходники','10 августа',0]]},{n:'Алексей',r:'',ts:[['Подготовить заказ','Сегодня 15:00',0]]},{n:'Дима',r:'',ts:[['Позвонить клиенту','Завтра',0]]}],pages:[{date:'8 августа',text:''}],p:0};
const save=()=>localStorage.setItem(KEY,JSON.stringify(d)), esc=x=>String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function notes(){let q=$('#search').value.toLowerCase(),f=$('.chips .active').dataset.f,a=d.notes.filter(n=>(!q||(n.t+n.b).toLowerCase().includes(q))&&(f==='all'||f==='fav'&&n.f||f==='task'&&n.task));$('#notesList').innerHTML=a.map(n=>`<article class="note ${n.done?'done':''}"><button class="notecheck" data-done="${n.id}">${n.done?'✓':''}</button><b>${esc(n.t)}</b><button class="star ${n.f?'on':''}" data-star="${n.id}">${n.f?'★':'☆'}</button></article>`).join('')||'<div style="padding:30px;text-align:center;color:#666">Ничего не найдено</div>';$$('[data-star]').forEach(x=>x.onclick=()=>{let n=d.notes.find(n=>n.id==x.dataset.star);n.f=!n.f;save();notes()});$$('[data-done]').forEach(x=>x.onclick=()=>{let n=d.notes.find(n=>n.id==x.dataset.done);n.done=!n.done;save();notes()})}
function groups(){$('#groups').innerHTML=d.groups.map((g,i)=>`<div class="group"><button class="grouphead"><span class="groupicon">${g.i}</span><span class="groupmain"><span class="groupname">${esc(g.n)}</span><span class="groupcount">${g.a.length} элементов</span></span><span>⌄</span></button><div class="groupbody">${g.a.map(x=>`<div class="groupitem">${esc(x)}</div>`).join('')}</div></div>`).join('');$$('.grouphead').forEach(x=>x.onclick=()=>x.parentElement.classList.toggle('open'))}
function employees(){$('#employeeList').innerHTML=d.emps.filter(e=>e.n.toLowerCase().includes($('#employeeSearch').value.toLowerCase())).map((e,i)=>{let done=e.ts.filter(x=>x[2]).length;return `<article class="employee"><button class="employeehead"><span class="avatar">${esc(e.n[0])}</span><span class="empinfo"><span class="empname">${esc(e.n)}</span><span class="empsub">${esc(e.r||'Сотрудник')} · ${e.ts.length-done} активных</span></span><span>⌄</span></button><div class="empdetail"><div class="stats"><div class="stat"><b>${e.ts.length}</b><small>ВСЕГО</small></div><div class="stat"><b>${e.ts.length-done}</b><small>АКТИВНЫЕ</small></div><div class="stat"><b>0</b><small>ПРОСРОЧЕНО</small></div><div class="stat"><b>${done}</b><small>ГОТОВО</small></div></div>${e.ts.map((t,j)=>`<div class="task ${t[2]?'done':''}"><button class="check" data-check="${i}:${j}">${t[2]?'✓':''}</button><span style="flex:1">${esc(t[0])}</span><small>${esc(t[1])}</small></div>`).join('')}<div class="empactions"><button data-addtask="${i}">＋ Задача</button><button data-shareemp="${i}">↗ Поделиться</button></div></div></article>`}).join('');$$('.employeehead').forEach(x=>x.onclick=()=>x.parentElement.classList.toggle('open'));$$('[data-check]').forEach(x=>x.onclick=e=>{e.stopPropagation();let [i,j]=x.dataset.check.split(':');d.emps[i].ts[j][2]^=1;save();employees()});$$('[data-addtask]').forEach(x=>x.onclick=e=>{e.stopPropagation();addTask(+x.dataset.addtask)});$$('[data-shareemp]').forEach(x=>x.onclick=e=>{e.stopPropagation();share(d.emps[+x.dataset.shareemp].ts.map(t=>(t[2]?'✓ ':'□ ')+t[0]+' — '+t[1]).join('\n'))})}
function modal(title,html,fn){$('#mtitle').textContent=title;$('#mbody').innerHTML=html;$('#modal').classList.add('show');$('#msubmit').onclick=()=>{fn();$('#modal').classList.remove('show')}}
function addEmployee(){modal('Новый сотрудник',`<div class="form"><input id="mn" placeholder="Имя"><input id="mr" placeholder="Должность"><button id="msubmit" class="submit">Добавить</button></div>`,()=>{d.emps.push({n:$('#mn').value||'Новый сотрудник',r:$('#mr').value,ts:[]});save();employees()})}
function addTask(i){modal('Новая задача',`<div class="form"><input id="mt" placeholder="Что сделать?"><input id="md" placeholder="Дата: сегодня / завтра / 15 августа"><input id="mti" placeholder="Время"><button id="msubmit" class="submit">Добавить</button></div>`,()=>{d.emps[i].ts.push([$('#mt').value||'Новая задача',($('#md').value||'Сегодня')+' '+($('#mti').value||''),0]);save();employees()})}
function addSection(){modal('Новый раздел',`<div class="form"><input id="ms" placeholder="Название"><select id="mi"><option>▣</option><option>💼</option><option>📦</option><option>👥</option><option>📄</option><option>💡</option><option>🚚</option><option>🤝</option><option>⋯</option></select><button id="msubmit" class="submit">Создать</button></div>`,()=>{d.groups.push({n:$('#ms').value||'Новый раздел',i:$('#mi').value,a:[]});save();groups()})}
function screen(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav button').forEach(x=>x.classList.toggle('active',x.dataset.s===id))}
function page(){let p=d.pages[d.p];$('#counter').textContent=`${d.p+1} / ${d.pages.length}`;$('#pageDate').textContent=p.date;$('#pageText').value=p.text}function savePage(){d.pages[d.p].text=$('#pageText').value;save()}function share(t){if(navigator.share)navigator.share({text:t}).catch(()=>{});else navigator.clipboard?.writeText(t)}
$$('nav button[data-s]').forEach(x=>x.onclick=()=>screen(x.dataset.s));$$('.chips button').forEach(x=>x.onclick=()=>{$$('.chips button').forEach(y=>y.classList.remove('active'));x.classList.add('active');notes()});$('#search').oninput=notes;$('#employeeSearch').oninput=employees;$('#addEmployee').onclick=addEmployee;$('#addSection').onclick=addSection;$('#mclose').onclick=()=>$('#modal').classList.remove('show');$('#theme').onclick=()=>document.body.classList.toggle('light');$('#back').onclick=()=>screen('notes');$('#more').onclick=()=>share(d.pages[d.p].text);$('#share').onclick=()=>{savePage();share(d.pages[d.p].text)};$('#pageText').oninput=savePage;$('#newPage').onclick=()=>{savePage();d.pages.splice(d.p+1,0,{date:new Date().toLocaleDateString('ru-RU',{day:'numeric',month:'long'}),text:''});d.p++;save();page()};$('#delPage').onclick=()=>{if(d.pages.length>1){d.pages.splice(d.p,1);d.p=Math.max(0,d.p-1);save();page()}};
let sx=0;$('#paperWrap').ontouchstart=e=>sx=e.touches[0].clientX;$('#paperWrap').ontouchend=e=>{let dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>60){savePage();if(dx<0&&d.p<d.pages.length-1)d.p++;if(dx>0&&d.p>0)d.p--;save();page()}};

function openSettings(){screen('settings')}
function calculator(){modal('Калькулятор',`<div class="form"><input id="calcInput" inputmode="decimal" placeholder="Например: 125*3+40"><button id="msubmit" class="submit">Посчитать</button><div id="calcResult" style="padding:14px;border:1px solid #292832;border-radius:14px;color:#b9b4c2">Результат появится здесь</div></div>`,()=>{let v=$('#calcInput').value;try{let r=Function('return ('+v.replace(/[^0-9+\-*/().% ]/g,'')+')')();$('#calcResult').textContent=String(r)}catch{$('#calcResult').textContent='Проверьте выражение'}})}
function toggleNotes(){document.querySelector('.notesbox').classList.toggle('expanded')}
$('#settingsBtn').onclick=openSettings;$('#calcBtn').onclick=calculator;$('#calendar').onclick=()=>modal('Календарь',`<div style="padding:10px;color:#aaa">Календарь месяца подготовлен для следующего шага: выбор даты будет открывать задачи и заметки этого дня.</div><button id="msubmit" class="submit">Закрыть</button>`,()=>{});$('#expand').onclick=toggleNotes;

let rec=null,recording=false;function startVoice(){let SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert('Голосовое распознавание недоступно в этом браузере. Откройте приложение через Safari на iPhone.');return}rec=new SR();rec.lang='ru-RU';rec.continuous=true;rec.interimResults=true;let final='';rec.onresult=e=>{let inter='';for(let i=e.resultIndex;i<e.results.length;i++){let t=e.results[i][0].transcript;e.results[i].isFinal?final+=t+' ':inter+=t}$('#voiceStatus').textContent=final+inter||'Слушаю…'};rec.onend=()=>{if(recording)try{rec.start()}catch{}};rec.start();recording=true;$('#voice').classList.add('recording');$('#voiceStatus').textContent='Слушаю… отпустите кнопку';$('#voice').dataset.final=''}function stopVoice(){if(!rec)return;recording=false;rec.onend=null;rec.stop();$('#voice').classList.remove('recording');let text=$('#voiceStatus').textContent.trim();if(text&&!text.startsWith('Слушаю')){d.notes.unshift({id:Date.now(),t:text.split(/\s+/).slice(0,6).join(' '),b:text,m:'Сегодня, '+new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}),f:false,task:false});save();notes()}$('#voiceStatus').textContent='Готов к голосовой команде'}$('#voice').onpointerdown=e=>{e.preventDefault();startVoice()};['pointerup','pointercancel','pointerleave'].forEach(x=>$('#voice').addEventListener(x,e=>{e.preventDefault();stopVoice()}));
const navMic=$('#navMic');navMic.onpointerdown=e=>{e.preventDefault();startVoice();navMic.classList.add('recording')};['pointerup','pointercancel','pointerleave'].forEach(x=>navMic.addEventListener(x,e=>{e.preventDefault();stopVoice();navMic.classList.remove('recording')}));
notes();groups();employees();page();
